
sudo: false
language:
  - python
  - node_js
python: "2.7"
node_js: "0.10"
install:
  - "bin/bootstrap"
script: bin/test
cache:
  directories:
  - $HOME/.local/share/waldmeta
  - node_modules

notifications:
  irc: "chat.freenode.net##senet"
  email: false

